<?php

namespace Database\Seeders;

use App\Models\Congregation;
use App\Models\Menu;
use Illuminate\Database\Seeder;

class MenuCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $menus = collect([
            ['name' => 'Tocanita de pui cu mamaliguta si muraturi', 'type' => 'main', 'instructions' => 'Se serveste calda, cu mamaliguta si muraturi.', 'ingredients' => [['name' => 'Pulpe de pui dezosate', 'quantity_per_person' => 0.15, 'unit' => 'kg'], ['name' => 'Ceapa si morcovi', 'quantity_per_person' => 0.05, 'unit' => 'kg'], ['name' => 'Malai', 'quantity_per_person' => 0.08, 'unit' => 'kg'], ['name' => 'Muraturi', 'quantity_per_person' => 0.1, 'unit' => 'kg']], 'allergens' => [], 'packaging_cost' => 1.25],
            ['name' => 'Pilaf sarbesc cu carne de porc si salata de varza', 'type' => 'main', 'instructions' => 'Serveste pilaful cald cu salata de varza separat.', 'ingredients' => [['name' => 'Carne de porc', 'quantity_per_person' => 0.12, 'unit' => 'kg'], ['name' => 'Orez rotund', 'quantity_per_person' => 0.08, 'unit' => 'kg'], ['name' => 'Mix legume', 'quantity_per_person' => 0.04, 'unit' => 'kg'], ['name' => 'Varza alba', 'quantity_per_person' => 0.12, 'unit' => 'kg']], 'allergens' => [], 'packaging_cost' => 1.1],
            ['name' => 'Penne Bolognese la cuptor cu cascaval', 'type' => 'main', 'instructions' => 'Adauga sosul si cascavalul inainte de coacere.', 'ingredients' => [['name' => 'Carne tocata amestec', 'quantity_per_person' => 0.12, 'unit' => 'kg'], ['name' => 'Paste penne', 'quantity_per_person' => 0.09, 'unit' => 'kg'], ['name' => 'Sos de rosii', 'quantity_per_person' => 0.08, 'unit' => 'kg'], ['name' => 'Cascaval', 'quantity_per_person' => 0.03, 'unit' => 'kg']], 'allergens' => ['Gluten', 'Lapte'], 'packaging_cost' => 1.15],
            ['name' => 'Mazare scazuta cu piept de pui si paine', 'type' => 'main', 'instructions' => 'Serveste mazarea calda cu paine feliata.', 'ingredients' => [['name' => 'Piept de pui feliat', 'quantity_per_person' => 0.13, 'unit' => 'kg'], ['name' => 'Mazare', 'quantity_per_person' => 0.15, 'unit' => 'kg'], ['name' => 'Paine feliata', 'quantity_per_person' => 2, 'unit' => 'buc']], 'allergens' => ['Gluten'], 'packaging_cost' => 1.1],
            ['name' => 'Varza calita cu carnati si mamaliga', 'type' => 'main', 'instructions' => 'Gateste varza pana scade bine si serveste cu mamaliga.', 'ingredients' => [['name' => 'Carnati', 'quantity_per_person' => 0.12, 'unit' => 'kg'], ['name' => 'Varza alba', 'quantity_per_person' => 0.25, 'unit' => 'kg'], ['name' => 'Malai', 'quantity_per_person' => 0.08, 'unit' => 'kg']], 'allergens' => [], 'packaging_cost' => 1.15],
            ['name' => 'Chiftelute marinate cu piure de cartofi', 'type' => 'main', 'instructions' => 'Portioneaza chiftelutele cu sos si piureul separat.', 'ingredients' => [['name' => 'Carne tocata', 'quantity_per_person' => 0.12, 'unit' => 'kg'], ['name' => 'Cartofi', 'quantity_per_person' => 0.3, 'unit' => 'kg'], ['name' => 'Lapte si unt', 'quantity_per_person' => 0.04, 'unit' => 'kg'], ['name' => 'Sos de rosii', 'quantity_per_person' => 0.06, 'unit' => 'kg']], 'allergens' => ['Lapte'], 'packaging_cost' => 1.2],
            ['name' => 'Cartofi taranesti la cuptor cu costita si salata de sfecla', 'type' => 'main', 'instructions' => 'Serveste salata de sfecla separat.', 'ingredients' => [['name' => 'Cartofi', 'quantity_per_person' => 0.3, 'unit' => 'kg'], ['name' => 'Costita afumata', 'quantity_per_person' => 0.08, 'unit' => 'kg'], ['name' => 'Ceapa si boia', 'quantity_per_person' => 0.03, 'unit' => 'kg'], ['name' => 'Sfecla rosie murata', 'quantity_per_person' => 0.1, 'unit' => 'kg']], 'allergens' => [], 'packaging_cost' => 1.15],
            ['name' => 'Ostropel cremos de pui cu orez simplu', 'type' => 'main', 'instructions' => 'Pastreaza sosul si orezul calde pana la ambalare.', 'ingredients' => [['name' => 'Pulpe de pui', 'quantity_per_person' => 0.15, 'unit' => 'kg'], ['name' => 'Sos de rosii si usturoi', 'quantity_per_person' => 0.07, 'unit' => 'kg'], ['name' => 'Orez', 'quantity_per_person' => 0.08, 'unit' => 'kg']], 'allergens' => [], 'packaging_cost' => 1.15],
            ['name' => 'Varza a la Cluj', 'type' => 'main', 'instructions' => 'Asaza ingredientele in straturi si serveste cu smantana.', 'ingredients' => [['name' => 'Carne tocata', 'quantity_per_person' => 0.12, 'unit' => 'kg'], ['name' => 'Varza tocata', 'quantity_per_person' => 0.2, 'unit' => 'kg'], ['name' => 'Orez', 'quantity_per_person' => 0.05, 'unit' => 'kg'], ['name' => 'Smantana', 'quantity_per_person' => 0.03, 'unit' => 'kg']], 'allergens' => ['Lapte'], 'packaging_cost' => 1.2],
            ['name' => 'Iahnie de fasole cu afumatura si gogonele', 'type' => 'main', 'instructions' => 'Fierbe fasolea din timp si serveste cu gogonele.', 'ingredients' => [['name' => 'Fasole boabe uscata', 'quantity_per_person' => 0.09, 'unit' => 'kg'], ['name' => 'Ciolan afumat dezosat', 'quantity_per_person' => 0.08, 'unit' => 'kg'], ['name' => 'Gogonele', 'quantity_per_person' => 0.1, 'unit' => 'kg']], 'allergens' => [], 'packaging_cost' => 1.15],
            ['name' => 'Papricas de pui cu galuste de faina', 'type' => 'main', 'instructions' => 'Galustele se pregatesc proaspete; serveste imediat.', 'ingredients' => [['name' => 'Carne de pui', 'quantity_per_person' => 0.15, 'unit' => 'kg'], ['name' => 'Faina si oua', 'quantity_per_person' => 0.06, 'unit' => 'kg'], ['name' => 'Smantana de gatit', 'quantity_per_person' => 0.03, 'unit' => 'kg']], 'allergens' => ['Gluten', 'Oua', 'Lapte'], 'packaging_cost' => 1.15],
            ['name' => 'Tocana de ciuperci cu pui si mamaliga', 'type' => 'main', 'instructions' => 'Serveste tocanita calda cu mamaliga.', 'ingredients' => [['name' => 'Ciuperci champignon', 'quantity_per_person' => 0.1, 'unit' => 'kg'], ['name' => 'Piept sau pulpe de pui', 'quantity_per_person' => 0.1, 'unit' => 'kg'], ['name' => 'Malai', 'quantity_per_person' => 0.08, 'unit' => 'kg']], 'allergens' => [], 'packaging_cost' => 1.15],
            ['name' => 'Ciorba de legume', 'type' => 'soup', 'instructions' => 'Serveste ciorba calda in recipiente separate.', 'ingredients' => [['name' => 'Mix legume pentru ciorba', 'quantity_per_person' => 0.2, 'unit' => 'kg'], ['name' => 'Bors', 'quantity_per_person' => 0.05, 'unit' => 'l']], 'allergens' => ['Telina'], 'packaging_cost' => 0],
            ['name' => 'Ciorba de perisoare', 'type' => 'soup', 'instructions' => 'Serveste ciorba calda in recipiente separate.', 'ingredients' => [['name' => 'Carne tocata pentru perisoare', 'quantity_per_person' => 0.07, 'unit' => 'kg'], ['name' => 'Legume pentru ciorba', 'quantity_per_person' => 0.15, 'unit' => 'kg'], ['name' => 'Orez', 'quantity_per_person' => 0.02, 'unit' => 'kg'], ['name' => 'Bors', 'quantity_per_person' => 0.05, 'unit' => 'l']], 'allergens' => ['Gluten', 'Oua', 'Telina'], 'packaging_cost' => 0],
            ['name' => 'Ciorba a la grec', 'type' => 'soup', 'instructions' => 'Adauga smantana si lamaie la final, inainte de portionare.', 'ingredients' => [['name' => 'Carne de pui', 'quantity_per_person' => 0.1, 'unit' => 'kg'], ['name' => 'Legume pentru ciorba', 'quantity_per_person' => 0.15, 'unit' => 'kg'], ['name' => 'Orez', 'quantity_per_person' => 0.02, 'unit' => 'kg'], ['name' => 'Smantana', 'quantity_per_person' => 0.03, 'unit' => 'kg']], 'allergens' => ['Lapte', 'Telina'], 'packaging_cost' => 0],
            ['name' => 'Supa cu galuste', 'type' => 'soup', 'instructions' => 'Galustele se pregatesc proaspete si se adauga inainte de servire.', 'ingredients' => [['name' => 'Carne de pui', 'quantity_per_person' => 0.08, 'unit' => 'kg'], ['name' => 'Legume pentru supa', 'quantity_per_person' => 0.15, 'unit' => 'kg'], ['name' => 'Faina si oua', 'quantity_per_person' => 0.04, 'unit' => 'kg']], 'allergens' => ['Gluten', 'Oua', 'Telina'], 'packaging_cost' => 0],
        ])->map(fn (array $menu) => Menu::firstOrCreate(['name' => $menu['name']], $menu + ['is_active' => true]));

        Congregation::query()->each(fn (Congregation $congregation) => $congregation->menus()
            ->syncWithoutDetaching($menus->pluck('id')->all()));
    }
}